# Generated by Django 5.0.2 on 2024-04-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='boards/')),
                ('description', models.TextField()),
                ('number', models.IntegerField()),
                ('shaper', models.CharField(max_length=100)),
            ],
        ),
    ]
