# Generated by Django 5.0.2 on 2024-04-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenapp', '0002_boards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boards',
            new_name='Board',
        ),
    ]
